/** Catálogo cerrado de códigos de error propios de @dwm/scheduler, con prefijo `SCHEDULER_`. */
export enum SchedulerErrorCode {
  SCHEDULER_INVALID_TASK_OPTIONS = "SCHEDULER_INVALID_TASK_OPTIONS",
  SCHEDULER_INVALID_CRON_EXPRESSION = "SCHEDULER_INVALID_CRON_EXPRESSION",
  SCHEDULER_TASK_NOT_FOUND = "SCHEDULER_TASK_NOT_FOUND",
  SCHEDULER_DUPLICATE_TASK_ID = "SCHEDULER_DUPLICATE_TASK_ID",
  SCHEDULER_TASK_TIMEOUT = "SCHEDULER_TASK_TIMEOUT",
  SCHEDULER_TASK_EXECUTION_FAILED = "SCHEDULER_TASK_EXECUTION_FAILED",
  SCHEDULER_SHUTTING_DOWN = "SCHEDULER_SHUTTING_DOWN",
}
