/** Catálogo cerrado de códigos de error propios de @dwm/profile, con prefijo `PROFILE_`. */
export enum ProfileErrorCode {
  PROFILE_INVALID_CONFIGURATION = "PROFILE_INVALID_CONFIGURATION",
  PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS",
  PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND",
  PROFILE_INVALID_STATE_TRANSITION = "PROFILE_INVALID_STATE_TRANSITION",
  PROFILE_VALIDATION_FAILED = "PROFILE_VALIDATION_FAILED",
  PROFILE_LOAD_FAILED = "PROFILE_LOAD_FAILED",
  PROFILE_SAVE_FAILED = "PROFILE_SAVE_FAILED",
  PROFILE_DELETE_FAILED = "PROFILE_DELETE_FAILED",
  PROFILE_IMPORT_FAILED = "PROFILE_IMPORT_FAILED",
  PROFILE_ACTIVATION_FAILED = "PROFILE_ACTIVATION_FAILED",
}
