/** Catálogo cerrado de códigos de error propios de @dwm/rule-manager, con prefijo `RULE_`. */
export enum RuleErrorCode {
  RULE_INVALID_REQUEST = "RULE_INVALID_REQUEST",
  RULE_INVALID_ID = "RULE_INVALID_ID",
  RULE_NOT_FOUND = "RULE_NOT_FOUND",
  RULE_ALREADY_EXISTS = "RULE_ALREADY_EXISTS",
  RULE_DIRECTORY_UNRESOLVABLE = "RULE_DIRECTORY_UNRESOLVABLE",
  RULE_READ_FAILED = "RULE_READ_FAILED",
  RULE_WRITE_FAILED = "RULE_WRITE_FAILED",
  RULE_DELETE_FAILED = "RULE_DELETE_FAILED",
  RULE_LIST_FAILED = "RULE_LIST_FAILED",
  RULE_VALIDATION_FAILED = "RULE_VALIDATION_FAILED",
  RULE_INVALID_STRUCTURE = "RULE_INVALID_STRUCTURE",
  RULE_ALREADY_ARCHIVED = "RULE_ALREADY_ARCHIVED",
  RULE_NOT_ARCHIVED = "RULE_NOT_ARCHIVED",
}
