/** Catálogo cerrado de códigos de error propios de @dwm/project-provisioning, con prefijo `PROVISIONING_`. */
export enum ProjectProvisioningErrorCode {
  PROVISIONING_INVALID_REQUEST = "PROVISIONING_INVALID_REQUEST",
  PROVISIONING_PSN_BASE_NOT_FOUND = "PROVISIONING_PSN_BASE_NOT_FOUND",
  PROVISIONING_NO_ACTIVE_PROFILE = "PROVISIONING_NO_ACTIVE_PROFILE",
  PROVISIONING_UNSAFE_PATH = "PROVISIONING_UNSAFE_PATH",
  PROVISIONING_DESTINATION_EXISTS = "PROVISIONING_DESTINATION_EXISTS",
  PROVISIONING_COPY_FAILED = "PROVISIONING_COPY_FAILED",
  PROVISIONING_ROLLBACK_FAILED = "PROVISIONING_ROLLBACK_FAILED",
  /** Fallo real de la IA (respuesta no interpretable, sin proveedor configurado, etc.) — encargo cierre de limitaciones, item 6. */
  PROVISIONING_AI_FAILED = "PROVISIONING_AI_FAILED",
}
