/** Catálogo cerrado de códigos de error propios de @dwm/tooling, con prefijo `TOOL_`. */
export enum ToolErrorCode {
  TOOL_INVALID_CONFIGURATION = "TOOL_INVALID_CONFIGURATION",
  TOOL_ALREADY_REGISTERED = "TOOL_ALREADY_REGISTERED",
  TOOL_NOT_FOUND = "TOOL_NOT_FOUND",
  TOOL_MISSING_DEPENDENCY = "TOOL_MISSING_DEPENDENCY",
  TOOL_DEPENDENCY_CYCLE = "TOOL_DEPENDENCY_CYCLE",
  TOOL_INVALID_STATE_TRANSITION = "TOOL_INVALID_STATE_TRANSITION",
  TOOL_INIT_FAILED = "TOOL_INIT_FAILED",
  TOOL_ACTIVATE_FAILED = "TOOL_ACTIVATE_FAILED",
  TOOL_DEACTIVATE_FAILED = "TOOL_DEACTIVATE_FAILED",
  TOOL_REMOVE_FAILED = "TOOL_REMOVE_FAILED",
  TOOL_HEALTH_CHECK_FAILED = "TOOL_HEALTH_CHECK_FAILED",
  TOOL_INCOMPATIBLE = "TOOL_INCOMPATIBLE",
  TOOL_CONFLICT = "TOOL_CONFLICT",
}
