/** Catálogo cerrado de códigos de error propios de @dwm/application-api, con prefijo `APP_`. */
export enum ApplicationErrorCode {
  APP_UNKNOWN_OPERATION = "APP_UNKNOWN_OPERATION",
  APP_INVALID_REQUEST = "APP_INVALID_REQUEST",
  APP_INVALID_REQUEST_ID = "APP_INVALID_REQUEST_ID",
  APP_DUPLICATE_REQUEST_ID = "APP_DUPLICATE_REQUEST_ID",
  APP_INVALID_PAYLOAD = "APP_INVALID_PAYLOAD",
  APP_FIELD_TOO_LARGE = "APP_FIELD_TOO_LARGE",
  APP_PATH_TRAVERSAL = "APP_PATH_TRAVERSAL",
  APP_UNAUTHORIZED_ABSOLUTE_PATH = "APP_UNAUTHORIZED_ABSOLUTE_PATH",
  APP_PERMISSION_DENIED = "APP_PERMISSION_DENIED",
  APP_CONFIRMATION_REQUIRED = "APP_CONFIRMATION_REQUIRED",
  APP_VERSION_CONFLICT = "APP_VERSION_CONFLICT",
  APP_OPERATION_NOT_FOUND = "APP_OPERATION_NOT_FOUND",
  APP_OPERATION_CANCELLED = "APP_OPERATION_CANCELLED",
  APP_CANCELLATION_NOT_SUPPORTED = "APP_CANCELLATION_NOT_SUPPORTED",
  APP_DEPENDENCY_UNAVAILABLE = "APP_DEPENDENCY_UNAVAILABLE",
  APP_INTERNAL_ERROR = "APP_INTERNAL_ERROR",
}
