/** Catálogo cerrado de códigos de error propios de @dwm/workspace, con prefijo `WORKSPACE_`. */
export enum WorkspaceErrorCode {
  WORKSPACE_INVALID_PATH = "WORKSPACE_INVALID_PATH",
  WORKSPACE_ALREADY_EXISTS = "WORKSPACE_ALREADY_EXISTS",
  WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND",
  WORKSPACE_NOT_A_WORKSPACE = "WORKSPACE_NOT_A_WORKSPACE",
  WORKSPACE_ALREADY_OPEN = "WORKSPACE_ALREADY_OPEN",
  WORKSPACE_INVALID_CONFIGURATION = "WORKSPACE_INVALID_CONFIGURATION",
  WORKSPACE_SCAN_FAILED = "WORKSPACE_SCAN_FAILED",
  WORKSPACE_CLOSED = "WORKSPACE_CLOSED",
  WORKSPACE_LOAD_FAILED = "WORKSPACE_LOAD_FAILED",
  WORKSPACE_SAVE_FAILED = "WORKSPACE_SAVE_FAILED",
}
