/** Catálogo cerrado de códigos de error propios de @dwm/adapters, con prefijo `ADAPTER_`. */
export enum AdapterErrorCode {
  ADAPTER_INVALID_CONFIGURATION = "ADAPTER_INVALID_CONFIGURATION",
  ADAPTER_ALREADY_REGISTERED = "ADAPTER_ALREADY_REGISTERED",
  ADAPTER_NOT_FOUND = "ADAPTER_NOT_FOUND",
  ADAPTER_MISSING_DEPENDENCY = "ADAPTER_MISSING_DEPENDENCY",
  ADAPTER_DEPENDENCY_CYCLE = "ADAPTER_DEPENDENCY_CYCLE",
  ADAPTER_INVALID_STATE_TRANSITION = "ADAPTER_INVALID_STATE_TRANSITION",
  ADAPTER_INIT_FAILED = "ADAPTER_INIT_FAILED",
  ADAPTER_ACTIVATE_FAILED = "ADAPTER_ACTIVATE_FAILED",
  ADAPTER_DEACTIVATE_FAILED = "ADAPTER_DEACTIVATE_FAILED",
  ADAPTER_DISPOSE_FAILED = "ADAPTER_DISPOSE_FAILED",
  ADAPTER_HEALTH_CHECK_FAILED = "ADAPTER_HEALTH_CHECK_FAILED",
}
