/** Catálogo cerrado de códigos de error propios de @dwm/event-bus, con prefijo `EVENTBUS_`. */
export enum EventBusErrorCode {
  EVENTBUS_INVALID_PATTERN = "EVENTBUS_INVALID_PATTERN",
  EVENTBUS_INVALID_SUBSCRIPTION = "EVENTBUS_INVALID_SUBSCRIPTION",
  EVENTBUS_HANDLER_FAILED = "EVENTBUS_HANDLER_FAILED",
  EVENTBUS_MIDDLEWARE_FAILED = "EVENTBUS_MIDDLEWARE_FAILED",
}
