/** Catálogo cerrado de códigos de error propios de @dwm/environment-manager, con prefijo `ENVIRONMENT_`. */
export enum EnvironmentErrorCode {
  ENVIRONMENT_INVALID_REQUEST = "ENVIRONMENT_INVALID_REQUEST",
  ENVIRONMENT_INVALID_DETECTOR = "ENVIRONMENT_INVALID_DETECTOR",
  ENVIRONMENT_DETECTOR_ALREADY_REGISTERED = "ENVIRONMENT_DETECTOR_ALREADY_REGISTERED",
  ENVIRONMENT_DETECTOR_NOT_FOUND = "ENVIRONMENT_DETECTOR_NOT_FOUND",
  ENVIRONMENT_TOOL_NOT_FOUND = "ENVIRONMENT_TOOL_NOT_FOUND",
  ENVIRONMENT_INSPECTION_CANCELLED = "ENVIRONMENT_INSPECTION_CANCELLED",
  ENVIRONMENT_VARIABLE_NOT_AUTHORIZED = "ENVIRONMENT_VARIABLE_NOT_AUTHORIZED",
  ENVIRONMENT_INVALID_VERSION = "ENVIRONMENT_INVALID_VERSION",
  ENVIRONMENT_PROCESS_SPAWN_FAILED = "ENVIRONMENT_PROCESS_SPAWN_FAILED",
}
