/** Catálogo cerrado de códigos de error propios de @dwm/agent-manager, con prefijo `AGENT_`. */
export enum AgentErrorCode {
  AGENT_INVALID_REQUEST = "AGENT_INVALID_REQUEST",
  AGENT_INVALID_ID = "AGENT_INVALID_ID",
  AGENT_NOT_FOUND = "AGENT_NOT_FOUND",
  AGENT_ALREADY_EXISTS = "AGENT_ALREADY_EXISTS",
  AGENT_DIRECTORY_UNRESOLVABLE = "AGENT_DIRECTORY_UNRESOLVABLE",
  AGENT_READ_FAILED = "AGENT_READ_FAILED",
  AGENT_WRITE_FAILED = "AGENT_WRITE_FAILED",
  AGENT_DELETE_FAILED = "AGENT_DELETE_FAILED",
  AGENT_LIST_FAILED = "AGENT_LIST_FAILED",
  AGENT_VALIDATION_FAILED = "AGENT_VALIDATION_FAILED",
  AGENT_INVALID_STRUCTURE = "AGENT_INVALID_STRUCTURE",
  AGENT_ALREADY_ARCHIVED = "AGENT_ALREADY_ARCHIVED",
  AGENT_NOT_ARCHIVED = "AGENT_NOT_ARCHIVED",
}
