/**
 * Catálogo cerrado de códigos de error del Core (README §9).
 * Ampliarlo requiere revisión explícita; el código de producción no debe usar
 * cadenas libres para identificar errores.
 */
export enum ErrorCode {
  // Bootstrap / dependencias inyectadas
  INVALID_BOOTSTRAP_OPTIONS = "CORE_INVALID_BOOTSTRAP_OPTIONS",

  // Configuración
  CONFIG_LOAD_FAILED = "CORE_CONFIG_LOAD_FAILED",
  CONFIG_MALFORMED = "CORE_CONFIG_MALFORMED",

  // Perfil
  PROFILE_LOAD_FAILED = "CORE_PROFILE_LOAD_FAILED",

  // Ciclo de vida
  INVALID_LIFECYCLE_TRANSITION = "CORE_INVALID_LIFECYCLE_TRANSITION",
  NOT_READY = "CORE_NOT_READY",
  ALREADY_INITIALIZED = "CORE_ALREADY_INITIALIZED",
  INITIALIZATION_IN_PROGRESS = "CORE_INITIALIZATION_IN_PROGRESS",

  // Registro de módulos
  MODULE_ID_DUPLICATED = "CORE_MODULE_ID_DUPLICATED",
  MODULE_INVALID_IDENTITY = "CORE_MODULE_INVALID_IDENTITY",
  MODULE_CONTRACT_INCOMPATIBLE = "CORE_MODULE_CONTRACT_INCOMPATIBLE",
  MODULE_INIT_FAILED = "CORE_MODULE_INIT_FAILED",
  MODULE_NOT_FOUND = "CORE_MODULE_NOT_FOUND",
  MODULE_DISPOSE_FAILED = "CORE_MODULE_DISPOSE_FAILED",

  // Registro de adaptadores
  ADAPTER_ID_DUPLICATED = "CORE_ADAPTER_ID_DUPLICATED",
  ADAPTER_SUBJECT_ID_DUPLICATED = "CORE_ADAPTER_SUBJECT_ID_DUPLICATED",
  ADAPTER_INVALID_IDENTITY = "CORE_ADAPTER_INVALID_IDENTITY",
  ADAPTER_CONTRACT_INCOMPATIBLE = "CORE_ADAPTER_CONTRACT_INCOMPATIBLE",
  ADAPTER_INIT_FAILED = "CORE_ADAPTER_INIT_FAILED",
  ADAPTER_NOT_FOUND = "CORE_ADAPTER_NOT_FOUND",
  ADAPTER_DISPOSE_FAILED = "CORE_ADAPTER_DISPOSE_FAILED",

  // Versionado
  INVALID_SEMANTIC_VERSION = "CORE_INVALID_SEMANTIC_VERSION",

  // Eventos
  LISTENER_FAILED = "CORE_LISTENER_FAILED",
  RESERVED_EVENT_NAMESPACE = "CORE_RESERVED_EVENT_NAMESPACE",

  // Almacenamiento (contrato genérico, no específico de SO)
  STORAGE_READ_FAILED = "CORE_STORAGE_READ_FAILED",
  STORAGE_WRITE_FAILED = "CORE_STORAGE_WRITE_FAILED",
}
