/** Catálogo cerrado de códigos de error propios de @dwm/import-manager, con prefijo `IMPORT_`. */
export enum ImportErrorCode {
  IMPORT_NOT_FOUND = "IMPORT_NOT_FOUND",
  IMPORT_INVALID_REQUEST = "IMPORT_INVALID_REQUEST",
  IMPORT_SOURCE_NOT_FOUND = "IMPORT_SOURCE_NOT_FOUND",
  IMPORT_UNSAFE_PATH = "IMPORT_UNSAFE_PATH",
  IMPORT_DESTINATION_UNRESOLVABLE = "IMPORT_DESTINATION_UNRESOLVABLE",
  IMPORT_DESTINATION_EXISTS = "IMPORT_DESTINATION_EXISTS",
  IMPORT_SCAN_FAILED = "IMPORT_SCAN_FAILED",
  IMPORT_COPY_FAILED = "IMPORT_COPY_FAILED",
  IMPORT_INTEGRITY_MISMATCH = "IMPORT_INTEGRITY_MISMATCH",
  IMPORT_VALIDATION_FAILED = "IMPORT_VALIDATION_FAILED",
  IMPORT_OPERATION_CONFLICT = "IMPORT_OPERATION_CONFLICT",
  IMPORT_INVALID_STATE_TRANSITION = "IMPORT_INVALID_STATE_TRANSITION",
  IMPORT_CANCELLATION_NOT_ALLOWED = "IMPORT_CANCELLATION_NOT_ALLOWED",
  IMPORT_ROLLBACK_FAILED = "IMPORT_ROLLBACK_FAILED",
  IMPORT_PERSISTENCE_FAILED = "IMPORT_PERSISTENCE_FAILED",
}
