/** Catálogo cerrado de códigos de error propios de @dwm/restore, con prefijo `RESTORE_`. */
export enum RestoreErrorCode {
  RESTORE_NOT_FOUND = "RESTORE_NOT_FOUND",
  RESTORE_INVALID_REQUEST = "RESTORE_INVALID_REQUEST",
  RESTORE_BACKUP_NOT_FOUND = "RESTORE_BACKUP_NOT_FOUND",
  RESTORE_BACKUP_CORRUPTED = "RESTORE_BACKUP_CORRUPTED",
  RESTORE_INVALID_CHAIN = "RESTORE_INVALID_CHAIN",
  RESTORE_INCOMPATIBLE_FORMAT = "RESTORE_INCOMPATIBLE_FORMAT",
  RESTORE_INVALID_TARGET = "RESTORE_INVALID_TARGET",
  RESTORE_PROTECTED_RESOURCE = "RESTORE_PROTECTED_RESOURCE",
  RESTORE_OPERATION_CONFLICT = "RESTORE_OPERATION_CONFLICT",
  RESTORE_INVALID_STATE_TRANSITION = "RESTORE_INVALID_STATE_TRANSITION",
  RESTORE_APPLY_FAILED = "RESTORE_APPLY_FAILED",
  RESTORE_VERIFICATION_FAILED = "RESTORE_VERIFICATION_FAILED",
  RESTORE_CANCELLATION_NOT_ALLOWED = "RESTORE_CANCELLATION_NOT_ALLOWED",
  RESTORE_ROLLBACK_FAILED = "RESTORE_ROLLBACK_FAILED",
  RESTORE_PERSISTENCE_FAILED = "RESTORE_PERSISTENCE_FAILED",
  RESTORE_PROVIDER_ERROR = "RESTORE_PROVIDER_ERROR",
}
