/**
 * Catálogo cerrado de códigos de error propios de la capa host (TDS-001
 * §9.1), con prefijo `HOST_`. Ningún código se añade al catálogo cerrado
 * del propio Core; este catálogo es independiente y pertenece
 * exclusivamente a `@dwm/host`.
 */
export enum HostErrorCode {
  HOST_INVALID_CONFIGURATION = "HOST_INVALID_CONFIGURATION",
  HOST_INVALID_MANIFEST = "HOST_INVALID_MANIFEST",
  HOST_DEPENDENCY_MISSING = "HOST_DEPENDENCY_MISSING",
  HOST_CIRCULAR_DEPENDENCY = "HOST_CIRCULAR_DEPENDENCY",
  HOST_CAPABILITY_UNAVAILABLE = "HOST_CAPABILITY_UNAVAILABLE",
  HOST_MODULE_CONSTRUCTION_FAILED = "HOST_MODULE_CONSTRUCTION_FAILED",
  HOST_MODULE_REGISTRATION_FAILED = "HOST_MODULE_REGISTRATION_FAILED",
  HOST_ADAPTER_CONSTRUCTION_FAILED = "HOST_ADAPTER_CONSTRUCTION_FAILED",
  HOST_ADAPTER_REGISTRATION_FAILED = "HOST_ADAPTER_REGISTRATION_FAILED",
  HOST_CORE_INITIALIZATION_FAILED = "HOST_CORE_INITIALIZATION_FAILED",
  HOST_COMPONENT_SERVICE_UNAVAILABLE = "HOST_COMPONENT_SERVICE_UNAVAILABLE",
  HOST_USE_CASE_FAILED = "HOST_USE_CASE_FAILED",
  HOST_COMPOSITION_CANCELLED = "HOST_COMPOSITION_CANCELLED",
  HOST_COMPOSITION_ROLLBACK_FAILED = "HOST_COMPOSITION_ROLLBACK_FAILED",
  HOST_EXTERNAL_DEPENDENCY_DISPOSE_FAILED = "HOST_EXTERNAL_DEPENDENCY_DISPOSE_FAILED",
  HOST_SHUTDOWN_PARTIAL_FAILURE = "HOST_SHUTDOWN_PARTIAL_FAILURE",
  HOST_INVALID_STATE_TRANSITION = "HOST_INVALID_STATE_TRANSITION",
}
