/** Catálogo cerrado de códigos de error propios de @dwm/project, con prefijo `PROJECT_`. */
export enum ProjectErrorCode {
  PROJECT_INVALID_CONFIGURATION = "PROJECT_INVALID_CONFIGURATION",
  PROJECT_ALREADY_EXISTS = "PROJECT_ALREADY_EXISTS",
  PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND",
  PROJECT_INVALID_STATE_TRANSITION = "PROJECT_INVALID_STATE_TRANSITION",
  PROJECT_VALIDATION_FAILED = "PROJECT_VALIDATION_FAILED",
  PROJECT_LOAD_FAILED = "PROJECT_LOAD_FAILED",
  PROJECT_SAVE_FAILED = "PROJECT_SAVE_FAILED",
  PROJECT_DELETE_FAILED = "PROJECT_DELETE_FAILED",
  PROJECT_IMPORT_FAILED = "PROJECT_IMPORT_FAILED",
  PROJECT_OPEN_FAILED = "PROJECT_OPEN_FAILED",
  PROJECT_CLOSE_FAILED = "PROJECT_CLOSE_FAILED",
}
