/** Catálogo cerrado de códigos de error propios de @dwm/secrets, con prefijo `SECRETS_`. */
export enum SecretErrorCode {
  SECRETS_INVALID_CONFIGURATION = "SECRETS_INVALID_CONFIGURATION",
  SECRETS_INVALID_KEY = "SECRETS_INVALID_KEY",
  SECRETS_INVALID_VALUE = "SECRETS_INVALID_VALUE",
  SECRETS_NOT_FOUND = "SECRETS_NOT_FOUND",
  SECRETS_ALREADY_EXISTS = "SECRETS_ALREADY_EXISTS",
  SECRETS_ENCRYPTION_FAILED = "SECRETS_ENCRYPTION_FAILED",
  SECRETS_DECRYPTION_FAILED = "SECRETS_DECRYPTION_FAILED",
  SECRETS_LOAD_FAILED = "SECRETS_LOAD_FAILED",
  SECRETS_SAVE_FAILED = "SECRETS_SAVE_FAILED",
  SECRETS_DELETE_FAILED = "SECRETS_DELETE_FAILED",
  SECRETS_IMPORT_FAILED = "SECRETS_IMPORT_FAILED",
}
