/** Catálogo cerrado de códigos de error propios de @dwm/portable-package-manager, con prefijo `PACKAGE_`. */
export enum PortablePackageErrorCode {
  PACKAGE_INVALID_REQUEST = "PACKAGE_INVALID_REQUEST",
  PACKAGE_SOURCE_NOT_FOUND = "PACKAGE_SOURCE_NOT_FOUND",
  PACKAGE_BUILD_FAILED = "PACKAGE_BUILD_FAILED",
  PACKAGE_READ_FAILED = "PACKAGE_READ_FAILED",
  PACKAGE_EXTRACT_FAILED = "PACKAGE_EXTRACT_FAILED",
  PACKAGE_INVALID_MANIFEST = "PACKAGE_INVALID_MANIFEST",
  PACKAGE_INCOMPATIBLE_VERSION = "PACKAGE_INCOMPATIBLE_VERSION",
  PACKAGE_INTEGRITY_FAILED = "PACKAGE_INTEGRITY_FAILED",
  PACKAGE_UNSAFE_PATH = "PACKAGE_UNSAFE_PATH",
  PACKAGE_ZIP_SLIP = "PACKAGE_ZIP_SLIP",
  PACKAGE_SYMLINK_DENIED = "PACKAGE_SYMLINK_DENIED",
  PACKAGE_LIMIT_EXCEEDED = "PACKAGE_LIMIT_EXCEEDED",
  PACKAGE_CONFLICT = "PACKAGE_CONFLICT",
  PACKAGE_DESTINATION_UNSAFE = "PACKAGE_DESTINATION_UNSAFE",
  PACKAGE_CANCELLED = "PACKAGE_CANCELLED",
}
