/** Catálogo cerrado de códigos de error propios de @dwm/verification, con prefijo `VERIFICATION_`. */
export enum VerificationErrorCode {
  VERIFICATION_NOT_FOUND = "VERIFICATION_NOT_FOUND",
  VERIFICATION_INVALID_REQUEST = "VERIFICATION_INVALID_REQUEST",
  VERIFICATION_INVALID_STATE_TRANSITION = "VERIFICATION_INVALID_STATE_TRANSITION",
  VERIFICATION_OPERATION_CONFLICT = "VERIFICATION_OPERATION_CONFLICT",
  VERIFICATION_CHECK_FAILED = "VERIFICATION_CHECK_FAILED",
  VERIFICATION_PERSISTENCE_FAILED = "VERIFICATION_PERSISTENCE_FAILED",
}
