/** Catálogo cerrado de códigos de error propios de @dwm/ai-manager, con prefijo `AI_`. */
export enum AIErrorCode {
  AI_INVALID_CONFIGURATION = "AI_INVALID_CONFIGURATION",
  AI_PROVIDER_ALREADY_REGISTERED = "AI_PROVIDER_ALREADY_REGISTERED",
  AI_PROVIDER_NOT_FOUND = "AI_PROVIDER_NOT_FOUND",
  AI_NO_ACTIVE_PROVIDER = "AI_NO_ACTIVE_PROVIDER",
  AI_CREDENTIAL_MISSING = "AI_CREDENTIAL_MISSING",
  AI_REQUEST_TIMEOUT = "AI_REQUEST_TIMEOUT",
  AI_REQUEST_FAILED = "AI_REQUEST_FAILED",
  AI_HEALTH_CHECK_FAILED = "AI_HEALTH_CHECK_FAILED",
}
