/** Catálogo cerrado de códigos de error propios de @dwm/requirement-manager, con prefijo `REQUIREMENT_`. */
export enum RequirementErrorCode {
  REQUIREMENT_INVALID_ID = "REQUIREMENT_INVALID_ID",
  REQUIREMENT_INVALID_PAYLOAD = "REQUIREMENT_INVALID_PAYLOAD",
  REQUIREMENT_NOT_FOUND = "REQUIREMENT_NOT_FOUND",
  REQUIREMENT_ALREADY_EXISTS = "REQUIREMENT_ALREADY_EXISTS",
  REQUIREMENT_IO_ERROR = "REQUIREMENT_IO_ERROR",
}
