/** Catálogo cerrado de códigos de error propios de @dwm/portable-workspace, con prefijo `PWORKSPACE_`. */
export enum WorkspaceErrorCode {
  PWORKSPACE_NOT_FOUND = "PWORKSPACE_NOT_FOUND",
  PWORKSPACE_ALREADY_REGISTERED = "PWORKSPACE_ALREADY_REGISTERED",
  PWORKSPACE_INVALID_REQUEST = "PWORKSPACE_INVALID_REQUEST",
  PWORKSPACE_ROOT_NOT_LOCATED = "PWORKSPACE_ROOT_NOT_LOCATED",
  PWORKSPACE_INVALID_STRUCTURE = "PWORKSPACE_INVALID_STRUCTURE",
  PWORKSPACE_INVALID_METADATA = "PWORKSPACE_INVALID_METADATA",
  PWORKSPACE_PERMISSION_DENIED = "PWORKSPACE_PERMISSION_DENIED",
  PWORKSPACE_INITIALIZATION_FAILED = "PWORKSPACE_INITIALIZATION_FAILED",
  PWORKSPACE_VALIDATION_FAILED = "PWORKSPACE_VALIDATION_FAILED",
  PWORKSPACE_PERSISTENCE_FAILED = "PWORKSPACE_PERSISTENCE_FAILED",
}
