/** Catálogo cerrado de códigos de error propios de @dwm/config, con prefijo `CONFIG_`. */
export enum ConfigErrorCode {
  CONFIG_INVALID_CONFIGURATION = "CONFIG_INVALID_CONFIGURATION",
  CONFIG_INVALID_NAMESPACE = "CONFIG_INVALID_NAMESPACE",
  CONFIG_SECTION_NOT_FOUND = "CONFIG_SECTION_NOT_FOUND",
  CONFIG_LOAD_FAILED = "CONFIG_LOAD_FAILED",
  CONFIG_SAVE_FAILED = "CONFIG_SAVE_FAILED",
  CONFIG_DELETE_FAILED = "CONFIG_DELETE_FAILED",
}
