/** Catálogo cerrado de códigos de error propios de @dwm/status, con prefijo `STATUS_`. */
export enum StatusErrorCode {
  STATUS_PROVIDER_NOT_FOUND = "STATUS_PROVIDER_NOT_FOUND",
  STATUS_PROVIDER_ALREADY_REGISTERED = "STATUS_PROVIDER_ALREADY_REGISTERED",
  STATUS_INVALID_PROVIDER = "STATUS_INVALID_PROVIDER",
  STATUS_SNAPSHOT_NOT_FOUND = "STATUS_SNAPSHOT_NOT_FOUND",
  STATUS_PROVIDER_QUERY_FAILED = "STATUS_PROVIDER_QUERY_FAILED",
  STATUS_PERSISTENCE_FAILED = "STATUS_PERSISTENCE_FAILED",
  STATUS_INVALID_REQUEST = "STATUS_INVALID_REQUEST",
}
