/** Catálogo cerrado de códigos de error propios de @dwm/migration, con prefijo `MIGRATION_`. */
export enum MigrationErrorCode {
  MIGRATION_NOT_FOUND = "MIGRATION_NOT_FOUND",
  MIGRATION_INVALID_REQUEST = "MIGRATION_INVALID_REQUEST",
  MIGRATION_BACKUP_NOT_FOUND = "MIGRATION_BACKUP_NOT_FOUND",
  MIGRATION_INCOMPATIBLE_VERSION = "MIGRATION_INCOMPATIBLE_VERSION",
  MIGRATION_CONFLICT = "MIGRATION_CONFLICT",
  MIGRATION_INVALID_STATE_TRANSITION = "MIGRATION_INVALID_STATE_TRANSITION",
  MIGRATION_EXPORT_FAILED = "MIGRATION_EXPORT_FAILED",
  MIGRATION_IMPORT_FAILED = "MIGRATION_IMPORT_FAILED",
  MIGRATION_CANCELLATION_NOT_ALLOWED = "MIGRATION_CANCELLATION_NOT_ALLOWED",
  MIGRATION_ROLLBACK_FAILED = "MIGRATION_ROLLBACK_FAILED",
  MIGRATION_PERSISTENCE_FAILED = "MIGRATION_PERSISTENCE_FAILED",
  MIGRATION_OPERATION_CONFLICT = "MIGRATION_OPERATION_CONFLICT",
}
